package toyland_inventorysystem;

import java.awt.Color;
import java.awt.Font;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class accountCenter extends javax.swing.JFrame {

    public accountCenter() {
        initComponents();
        accountCenter.this.setLocationRelativeTo(null);
        jTable1.getTableHeader().setFont(new Font("SansSerif", Font.BOLD, 14));

        if (Toyland_InventorySystem.getGoTo_AccountCenter_of().equals("admin")) {
            jLabel2.setText("Administrator Accounts");
            int size = Toyland_InventorySystem.getAdminUsername().size(); 
            for (int i = 0; i < size;) {
                String id = Toyland_InventorySystem.getAdminAccID().get(i); 
                String name = Toyland_InventorySystem.getAdminName().get(i); 
                String userName = Toyland_InventorySystem.getAdminUsername().get(i); 
                String passWord = Toyland_InventorySystem.getAdminPassword().get(i); 
                Object[] row = {id, name, userName, passWord};
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(row);
                i++;
            }
        } else {
            jLabel2.setText("Employee Accounts");
            int size = Toyland_InventorySystem.getEmpUsername().size(); 
            for (int i = 0; i < size;) {
                String id = Toyland_InventorySystem.getEmpAccID().get(i); 
                String name = Toyland_InventorySystem.getEmpName().get(i); 
                String userName = Toyland_InventorySystem.getEmpUsername().get(i); 
                String passWord = Toyland_InventorySystem.getEmpPassword().get(i); 
                Object[] row = {id, name, userName, passWord};
                DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.addRow(row);
                i++;
            }
        }
        if (jTable1.getRowCount() == 0) {
            jLabel84.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel57 = new javax.swing.JLabel();
        jPanel34 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        jPanel35 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        jPanel36 = new javax.swing.JPanel();
        jTextField4 = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        jPanel37 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        jPanel64 = new javax.swing.JPanel();
        jLabel77 = new javax.swing.JLabel();
        jPanel66 = new javax.swing.JPanel();
        jLabel79 = new javax.swing.JLabel();
        jPanel67 = new javax.swing.JPanel();
        jLabel80 = new javax.swing.JLabel();
        jPanel68 = new javax.swing.JPanel();
        jLabel81 = new javax.swing.JLabel();
        jPanel70 = new javax.swing.JPanel();
        jLabel83 = new javax.swing.JLabel();
        jPanel71 = new javax.swing.JPanel();
        jLabel84 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1307, 790));

        jPanel1.setBackground(new java.awt.Color(255, 222, 89));

        jLabel57.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel57.setText("Name:*");

        jPanel34.setBackground(new java.awt.Color(0, 0, 0));
        jPanel34.setPreferredSize(new java.awt.Dimension(280, 15));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));

        javax.swing.GroupLayout jPanel34Layout = new javax.swing.GroupLayout(jPanel34);
        jPanel34.setLayout(jPanel34Layout);
        jPanel34Layout.setHorizontalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField2)
        );
        jPanel34Layout.setVerticalGroup(
            jPanel34Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel34Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel56.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel56.setText("Account ID:");

        jPanel35.setBackground(new java.awt.Color(0, 0, 0));
        jPanel35.setPreferredSize(new java.awt.Dimension(280, 15));

        jTextField3.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                name_Validation(evt);
            }
        });

        javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(jPanel35);
        jPanel35.setLayout(jPanel35Layout);
        jPanel35Layout.setHorizontalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField3)
        );
        jPanel35Layout.setVerticalGroup(
            jPanel35Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel35Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel58.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel58.setText("Username:*");

        jPanel36.setBackground(new java.awt.Color(0, 0, 0));
        jPanel36.setPreferredSize(new java.awt.Dimension(280, 15));

        jTextField4.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                username_Validation(evt);
            }
        });

        javax.swing.GroupLayout jPanel36Layout = new javax.swing.GroupLayout(jPanel36);
        jPanel36.setLayout(jPanel36Layout);
        jPanel36Layout.setHorizontalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField4)
        );
        jPanel36Layout.setVerticalGroup(
            jPanel36Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel36Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel59.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel59.setText("Password:*");

        jPanel37.setBackground(new java.awt.Color(0, 0, 0));
        jPanel37.setPreferredSize(new java.awt.Dimension(280, 15));

        jTextField5.setFont(new java.awt.Font("SansSerif", 0, 15)); // NOI18N
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                password_Validation(evt);
            }
        });

        jLabel60.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel60.setText("Account ID:");

        javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(jPanel37);
        jPanel37.setLayout(jPanel37Layout);
        jPanel37Layout.setHorizontalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTextField5)
        );
        jPanel37Layout.setVerticalGroup(
            jPanel37Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel37Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel64.setBackground(new java.awt.Color(151, 79, 255));

        jLabel77.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel77.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel77.setText("<html> ‎ ‎‎ Create<br>Account</html>\n");
        jLabel77.setToolTipText("");
        jLabel77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createAccount(evt);
            }
        });

        javax.swing.GroupLayout jPanel64Layout = new javax.swing.GroupLayout(jPanel64);
        jPanel64.setLayout(jPanel64Layout);
        jPanel64Layout.setHorizontalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel77, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel64Layout.setVerticalGroup(
            jPanel64Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel77, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel66.setBackground(new java.awt.Color(151, 79, 255));

        jLabel79.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel79.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel79.setText("Update");
        jLabel79.setToolTipText("");
        jLabel79.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                update(evt);
            }
        });

        javax.swing.GroupLayout jPanel66Layout = new javax.swing.GroupLayout(jPanel66);
        jPanel66.setLayout(jPanel66Layout);
        jPanel66Layout.setHorizontalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );
        jPanel66Layout.setVerticalGroup(
            jPanel66Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel79, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel67.setBackground(new java.awt.Color(151, 79, 255));

        jLabel80.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel80.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel80.setText("Clear");
        jLabel80.setToolTipText("");
        jLabel80.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clear(evt);
            }
        });

        javax.swing.GroupLayout jPanel67Layout = new javax.swing.GroupLayout(jPanel67);
        jPanel67.setLayout(jPanel67Layout);
        jPanel67Layout.setHorizontalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel80, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel67Layout.setVerticalGroup(
            jPanel67Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel80, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel68.setBackground(new java.awt.Color(151, 79, 255));

        jLabel81.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel81.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel81.setText("<html>‎‎‎ ‎‎ ‎   ‎ Edit<br>Account</html>\n");
        jLabel81.setToolTipText("");
        jLabel81.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editAccount(evt);
            }
        });

        javax.swing.GroupLayout jPanel68Layout = new javax.swing.GroupLayout(jPanel68);
        jPanel68.setLayout(jPanel68Layout);
        jPanel68Layout.setHorizontalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
        );
        jPanel68Layout.setVerticalGroup(
            jPanel68Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel70.setBackground(new java.awt.Color(151, 79, 255));

        jLabel83.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel83.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel83.setText("Exit");
        jLabel83.setToolTipText("");
        jLabel83.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exit(evt);
            }
        });

        javax.swing.GroupLayout jPanel70Layout = new javax.swing.GroupLayout(jPanel70);
        jPanel70.setLayout(jPanel70Layout);
        jPanel70Layout.setHorizontalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel70Layout.setVerticalGroup(
            jPanel70Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel83, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel71.setBackground(new java.awt.Color(151, 79, 255));

        jLabel84.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel84.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel84.setText("<html>Remove<br>Account</html> ");
        jLabel84.setToolTipText("");
        jLabel84.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeAccount(evt);
            }
        });

        javax.swing.GroupLayout jPanel71Layout = new javax.swing.GroupLayout(jPanel71);
        jPanel71.setLayout(jPanel71Layout);
        jPanel71Layout.setHorizontalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel84, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
        );
        jPanel71Layout.setVerticalGroup(
            jPanel71Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel84, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(151, 79, 255));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 33)); // NOI18N
        jLabel1.setText("Account Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel58)
                        .addComponent(jPanel37, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                        .addComponent(jPanel36, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                        .addComponent(jPanel35, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                        .addComponent(jPanel34, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                        .addComponent(jLabel57, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                        .addComponent(jLabel59, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel71, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPanel64, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel56, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel34, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel57, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel35, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel36, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jPanel37, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel66, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel64, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel67, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel68, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel71, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel70, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );

        jPanel1.setBounds(0, 0, 450, 760);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("SansSerif", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Account ID", "Name", "Username", "Password"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(24);
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setResizingAllowed(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);
        jTable1.getColumnModel().getColumn(3).setResizable(false);

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 40)); // NOI18N
        jLabel2.setText("Administrator Accounts");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jPanel3.setBounds(450, 0, 860, 760);
        jLayeredPane1.add(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1305, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 760, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearFields() {
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
    }
    private void exit(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exit
        accountCenter.this.setVisible(false);
        Toyland_InventorySystem.setGoTo_AccountCenter_of("");
    }//GEN-LAST:event_exit

    private void clear(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clear
        clearFields();
        jTable1.clearSelection();
    }//GEN-LAST:event_clear

    private void createAccount(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createAccount
        if (jTextField3.getText().isEmpty() || jTextField4.getText().isEmpty() || jTextField5.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please fill out all the required fields.", "INVALID INPUT", JOptionPane.ERROR_MESSAGE);
        } else {
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            boolean isSameUsername = false;
            int rowCount = model.getRowCount();

            if (Toyland_InventorySystem.getGoTo_AccountCenter_of().equals("admin")) {
                int ctr = Toyland_InventorySystem.getAdminUsername().size() + 1; 
                String id = "Admin#23-" + Integer.toString(ctr);
                String name = jTextField3.getText();
                String userName = jTextField4.getText();
                String passWord = jTextField5.getText();
                Object[] row = {id, name, userName, passWord};

                for (int rowNum = 0; rowNum < rowCount; rowNum++) {
                    Object cellValue = model.getValueAt(rowNum, 2);
                    if (cellValue != null && cellValue.toString().equals(userName)) {
                        isSameUsername = true;
                        JOptionPane.showMessageDialog(null, "Username is already taken.", "INVALID INPUT", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                }

                if (isSameUsername == false) {
                    model.addRow(row);
                    Toyland_InventorySystem.addAdminAccID(id);
                    Toyland_InventorySystem.addAdminName(jTextField3.getText());
                    Toyland_InventorySystem.addAdminUsername(jTextField4.getText());
                    Toyland_InventorySystem.addAdminPassword(jTextField5.getText());
                    JOptionPane.showMessageDialog(null, "ACCOUNT CREATED SUCCESSFULLY!");
                    jLabel84.setEnabled(true);
                }
            } else {
                int ctr = Toyland_InventorySystem.getEmpUsername().size() + 1; 
                String id = "Employee#23-" + Integer.toString(ctr);
                String name = jTextField3.getText();
                String userName = jTextField4.getText();
                String passWord = jTextField5.getText();
                Object[] row = {id, name, userName, passWord};

                for (int rowNum = 0; rowNum < rowCount; rowNum++) {
                    Object cellValue = model.getValueAt(rowNum, 2);
                    if (cellValue != null && cellValue.toString().equals(userName)) {
                        isSameUsername = true;
                        JOptionPane.showMessageDialog(null, "Username is already taken.", "INVALID INPUT", JOptionPane.ERROR_MESSAGE);
                        break;
                    }
                }

                if (isSameUsername == false) {
                    model.addRow(row);
                    Toyland_InventorySystem.addEmpAccID(id);
                    Toyland_InventorySystem.addEmpName(jTextField3.getText());
                    Toyland_InventorySystem.addEmpUsername(jTextField4.getText());
                    Toyland_InventorySystem.addEmpPassword(jTextField5.getText());
                    JOptionPane.showMessageDialog(null, "ACCOUNT CREATED SUCCESSFULLY!");
                    jLabel84.setEnabled(true);
                }
            }
            clearFields();
            jTable1.clearSelection();
        }
    }//GEN-LAST:event_createAccount

    private void name_Validation(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_name_Validation
        // Validation: Only Letters and Max Characters: 80
        String n = jTextField3.getText();
        int l1 = n.length();
        char c1 = evt.getKeyChar();
        if (Character.isLetter(c1)) {
            if (l1 < 40) {
                jTextField3.setEditable(true);
            } else {
                jTextField3.setEditable(false);
            }
        } else {
            if (Character.isWhitespace(c1) || Character.isISOControl(c1) || evt.getExtendedKeyCode() == KeyEvent.VK_SHIFT) {
                jTextField3.setEditable(true);
            } else {
                jTextField3.setEditable(false);
            }
        }
    }//GEN-LAST:event_name_Validation

    private void editAccount(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editAccount
        int row = jTable1.getSelectedRow();
        if (row > -1) {
            String id = jTable1.getValueAt(row, 0).toString();
            String name = jTable1.getValueAt(row, 1).toString();
            String userN = jTable1.getValueAt(row, 2).toString();
            String passW = jTable1.getValueAt(row, 3).toString();

            jTextField2.setText(id);
            jTextField3.setText(name);
            jTextField4.setText(userN);
            jTextField5.setText(passW);
        }
    }//GEN-LAST:event_editAccount

    private void update(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_update
        String id = "", name = "", userN = "", passW = "";
        Object is_selected_ID = null;
        int row = jTable1.getSelectedRow();
        if (row > -1) {
            is_selected_ID = jTable1.getValueAt(row, 0); // Get value of column 
            id = jTextField2.getText();
            name = jTextField3.getText();
            userN = jTextField4.getText();
            passW = jTextField5.getText();
        }

        if (is_selected_ID != null && is_selected_ID.equals(id)) {
            if (!id.trim().isEmpty() && !name.trim().isEmpty() && !userN.trim().isEmpty() && !passW.trim().isEmpty()) {
                jTable1.setValueAt(id, row, 0);
                jTable1.setValueAt(name, row, 1);
                jTable1.setValueAt(userN, row, 2);
                jTable1.setValueAt(passW, row, 3);

                if (Toyland_InventorySystem.getGoTo_AccountCenter_of().equals("admin")) {
                    Toyland_InventorySystem.setAdminAccID(row, id);
                    Toyland_InventorySystem.setAdminName(row, name);
                    Toyland_InventorySystem.setAdminUsername(row, userN);
                    Toyland_InventorySystem.setAdminPassword(row, passW);
                } else {
                    Toyland_InventorySystem.setEmpAccID(row, id);
                    Toyland_InventorySystem.setEmpName(row, name);
                    Toyland_InventorySystem.setEmpUsername(row, userN);
                    Toyland_InventorySystem.setEmpPassword(row, passW);
                }
                clearFields();
                jTable1.clearSelection();
                JOptionPane.showMessageDialog(null, "ACCOUNT UPDATED!");
            } else {
                JOptionPane.showMessageDialog(null, "Please fill out all the required fields.", "INVALID INPUT", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_update

    private void removeAccount(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeAccount
        int row = jTable1.getSelectedRow();
        if (row > -1) {
            int reply = JOptionPane.showConfirmDialog(null, "Are you sure you want to delete?");
            if (reply == JOptionPane.YES_OPTION) {
                ((DefaultTableModel) jTable1.getModel()).removeRow(jTable1.getSelectedRow());
                if (Toyland_InventorySystem.getGoTo_AccountCenter_of().equals("admin")) {
                    Toyland_InventorySystem.removeAdminAccID(row);
                    Toyland_InventorySystem.removeAdminName(row);
                    Toyland_InventorySystem.removeAdminUsername(row);
                    Toyland_InventorySystem.removeAdminPassword(row);
                } else {
                    Toyland_InventorySystem.removeEmpAccID(row);
                    Toyland_InventorySystem.removeEmpName(row);
                    Toyland_InventorySystem.removeEmpUsername(row);
                    Toyland_InventorySystem.removeEmpPassword(row);
                }
                JOptionPane.showMessageDialog(null, "ACCOUNT DELETED!");
                if (jTable1.getRowCount() == 0) {
                    jLabel84.setEnabled(false); // disable remove button if there is no account left 
                }
            }
        }
    }//GEN-LAST:event_removeAccount

    private void username_Validation(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_Validation
        // Validation: Maximum characters of 40 
        String n = jTextField4.getText();
        int l1 = n.length();
        char c1 = evt.getKeyChar();

        if (Character.isLetterOrDigit(c1)) {
            if (l1 < 40) {
                jTextField4.setEditable(true);
            } else {
                jTextField4.setEditable(false);
            }
        } else {
            if (Character.isWhitespace(c1) || Character.isISOControl(c1) || evt.getExtendedKeyCode() == KeyEvent.VK_2 || evt.getExtendedKeyCode() == KeyEvent.VK_SHIFT) {
                jTextField4.setEditable(true);
            } else {
                jTextField4.setEditable(false);
            }
        }
    }//GEN-LAST:event_username_Validation

    private void password_Validation(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_Validation
        // Validation: Maximum characters of 40 
        String n = jTextField5.getText();
        int l1 = n.length();
        char c1 = evt.getKeyChar();

        if (Character.isLetterOrDigit(c1)) {
            if (l1 < 40) {
                jTextField5.setEditable(true);
            } else {
                jTextField5.setEditable(false);
            }
        } else {
            if (Character.isWhitespace(c1) || Character.isISOControl(c1) || evt.getExtendedKeyCode() == KeyEvent.VK_2 || evt.getExtendedKeyCode() == KeyEvent.VK_SHIFT) {
                jTextField5.setEditable(true);
            } else {
                jTextField5.setEditable(false);
            }
        }
    }//GEN-LAST:event_password_Validation

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(accountCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new accountCenter().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JLabel jLabel84;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel37;
    private javax.swing.JPanel jPanel64;
    private javax.swing.JPanel jPanel66;
    private javax.swing.JPanel jPanel67;
    private javax.swing.JPanel jPanel68;
    private javax.swing.JPanel jPanel70;
    private javax.swing.JPanel jPanel71;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
