package toyland_inventorysystem;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class loginFrame extends javax.swing.JFrame {

    public loginFrame() {
        initComponents();
        loginFrame.this.setLocationRelativeTo(null);
        clear(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLabel11 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 222, 89));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginFrame - Inventory Picture.jpg"))); // NOI18N

        jLabel9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText(" Our powerful and user-friendly system provides monitoring and management into");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel9.setBounds(10, 60, 540, 19);
        jLayeredPane3.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Toyland's Inventory System ");
        jLabel8.setBounds(50, 13, 520, 47);
        jLayeredPane3.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("  our vast toy collection for employees, ensuring seamless operations.");
        jLabel10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel10.setBounds(70, 80, 460, 19);
        jLayeredPane3.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 380, Short.MAX_VALUE)
                .addGap(303, 303, 303))
        );

        jPanel1.setBounds(0, 0, 660, 640);
        jLayeredPane1.add(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel2.setBackground(new java.awt.Color(151, 79, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setMaximumSize(new java.awt.Dimension(100, 100));

        jPanel4.setBackground(new java.awt.Color(255, 222, 89));
        jPanel4.setMaximumSize(new java.awt.Dimension(0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(255, 222, 89));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 20)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Sign In");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signIn(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginFrame - Hide Password.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jLabel11.setBounds(260, 180, 30, 20);
        jLayeredPane2.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel7.setBackground(new java.awt.Color(151, 79, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(50, 35));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginFrame - Lock.png"))); // NOI18N
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel7.setBounds(20, 170, 40, 40);
        jLayeredPane2.add(jPanel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPanel6.setBackground(new java.awt.Color(151, 79, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginFrame - User.png"))); // NOI18N
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 40));

        jPanel6.setBounds(20, 90, 40, 40);
        jLayeredPane2.add(jPanel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setBackground(new java.awt.Color(241, 241, 241));
        jTextField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jTextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 10));
        jTextField1.setFocusTraversalPolicyProvider(true);
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField1FocusLost(evt);
            }
        });
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
                username_Validation(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });
        jTextField1.setBounds(60, 90, 240, 40);
        jLayeredPane2.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel2.setText("Username");
        jLabel2.setBounds(20, 70, 70, 19);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jPasswordField1.setBackground(new java.awt.Color(241, 241, 241));
        jPasswordField1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 10, 1, 45));
        jPasswordField1.setFocusTraversalPolicyProvider(true);
        jPasswordField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPasswordField1MouseClicked(evt);
            }
        });
        jPasswordField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPasswordField1FocusLost(evt);
            }
        });
        jPasswordField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyPressed(evt);
                password_Validation(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPasswordField1KeyReleased(evt);
            }
        });
        jPasswordField1.setBounds(60, 170, 240, 40);
        jLayeredPane2.add(jPasswordField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel3.setText("Password");
        jLabel3.setBounds(20, 150, 70, 19);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jLabel4.setText("Account Type");
        jLabel4.setBounds(20, 230, 120, 19);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setText("Login");
        jLabel1.setBounds(20, 0, 211, 74);
        jLayeredPane2.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jComboBox1.setBackground(new java.awt.Color(153, 102, 255));
        jComboBox1.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Employee", "Admin", "Super Admin" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jComboBox1.setFocusTraversalPolicyProvider(true);
        jComboBox1.setBounds(20, 250, 280, 40);
        jLayeredPane2.add(jComboBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel14.setText("Login");
        jLabel14.setBounds(20, 0, 211, 74);
        jLayeredPane2.add(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/LoginFrame - Logo Picture.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(41, 41, 41))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        jPanel2.setBounds(650, 0, 440, 640);
        jLayeredPane1.add(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1092, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        pic++;
        if (jPasswordField1.getForeground().getRGB() != new Color(0x8D8D8D).getRGB()) {
            if (pic % 2 == 0) {
                // Hide Password
                ImageIcon image = new ImageIcon("LoginFrame - Hide Password.png");
                jLabel11.setIcon(image);
                jPasswordField1.setEchoChar('*');
            } else {
                // Show Password 
                ImageIcon image = new ImageIcon("LoginFrame - View Password.png");
                jLabel11.setIcon(image);
                jPasswordField1.setEchoChar((char) 0);
            }
        }
    }//GEN-LAST:event_jLabel11MouseClicked

    private void goToMenu() {
        JOptionPane.showMessageDialog(null, "LOGIN SUCCESSFUL!");
        menuFrame menu = new menuFrame();
        menu.setVisible(true);
        loginFrame.this.setVisible(false);
    }

    private void userDoesNotExist() {
        JOptionPane.showMessageDialog(null, "Account does not exist!");
        clear();
    }

    private void clear() {
        jLabel5.requestFocus();
        jTextField1.setText("Enter Username");
        jTextField1.setForeground(new Color(0x8D8D8D));
        jPasswordField1.setText("Enter Password");
        jPasswordField1.setEchoChar((char) 0);
        jPasswordField1.setForeground(new Color(0x8D8D8D));
        jComboBox1.setSelectedIndex(-1);
        ImageIcon image = new ImageIcon("LoginFrame - Hide Password.png");
        jLabel11.setIcon(image);
        pic = 0;
    }

    private void signIn(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signIn
        if (jTextField1.getForeground().getRGB() == new Color(0x8D8D8D).getRGB() || jPasswordField1.getForeground().getRGB() == new Color(0x8D8D8D).getRGB() || jComboBox1.getSelectedIndex() == -1 || jTextField1.getText().isEmpty() || jPasswordField1.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Invalid Input. Please enter the Username / Password / Account Type");
            clear();
        } else {
            String type = jComboBox1.getSelectedItem().toString();
            int a;

            String uname1 = jTextField1.getText();
            String pass1 = jPasswordField1.getText();
            if (type.equalsIgnoreCase("Employee")) {
                a = Toyland_InventorySystem.getEmpUsername().size();
                if (Toyland_InventorySystem.getEmpUsername().indexOf(uname1) >= 0) {
                    for (int i = 0; i < a;) {
                        if (!uname1.equals(Toyland_InventorySystem.getEmpUsername().get(i))) {
                            i++;
                        } else {
                            if (!pass1.equals(Toyland_InventorySystem.getEmpPassword().get(i))) {
                                JOptionPane.showMessageDialog(null, "Invalid Input. Incorrect Username or Password.");
                                clear();
                                break;
                            } else {
                                Toyland_InventorySystem.setUserAccName(Toyland_InventorySystem.getEmpName().get(i));
                                Toyland_InventorySystem.setUserID(Toyland_InventorySystem.getEmpAccID().get(i));

                                Toyland_InventorySystem.addLogsAccNme(Toyland_InventorySystem.getEmpName().get(i));
                                Toyland_InventorySystem.addLogsAccTpe("Employee");
                                Toyland_InventorySystem.addLogsAccID(Toyland_InventorySystem.getEmpAccID().get(i));
                                Toyland_InventorySystem.setUserAccType("Employee");
                                goToMenu();
                                break;
                            }
                        }
                    }
                } else {
                    userDoesNotExist();
                }
            } else if (type.equalsIgnoreCase("Admin")) {
                a = Toyland_InventorySystem.getAdminUsername().size();
                if (Toyland_InventorySystem.getAdminUsername().indexOf(uname1) >= 0) {
                    for (int i = 0; i < a;) {
                        if (!uname1.equals(Toyland_InventorySystem.getAdminUsername().get(i))) {
                            i++;
                        } else {
                            if (!pass1.equals(Toyland_InventorySystem.getAdminPassword().get(i))) {
                                JOptionPane.showMessageDialog(null, "Invalid Input. Incorrect Username or Password");
                                clear();
                                break;
                            } else {
                                Toyland_InventorySystem.setUserAccName(Toyland_InventorySystem.getAdminName().get(i));
                                Toyland_InventorySystem.setUserID(Toyland_InventorySystem.getAdminAccID().get(i));

                                Toyland_InventorySystem.addLogsAccNme(Toyland_InventorySystem.getAdminName().get(i));
                                Toyland_InventorySystem.addLogsAccTpe("Admin");
                                Toyland_InventorySystem.addLogsAccID(Toyland_InventorySystem.getAdminAccID().get(i));
                                Toyland_InventorySystem.setUserAccType("Admin");
                                goToMenu();
                                break;
                            }
                        }
                    }
                } else {
                    userDoesNotExist();
                }
            } else {
                if (uname1.equals("SUPERADMIN") && pass1.equals("SUPERADMIN")) {
                    Toyland_InventorySystem.setUserAccName("Super Admin");
                    Toyland_InventorySystem.setUserID("SuperAdmin#23-1");

                    Toyland_InventorySystem.addLogsAccNme("Super Admin");
                    Toyland_InventorySystem.addLogsAccTpe("Super Admin");
                    Toyland_InventorySystem.addLogsAccID("SuperAdmin#23-1");
                    Toyland_InventorySystem.setUserAccType("Super Admin");
                    goToMenu();
                } else {
                    JOptionPane.showMessageDialog(null, "Invalid Input. Incorrect Username or Password");
                    clear();
                }
            }
        }

    }//GEN-LAST:event_signIn

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        if (jTextField1.getText().equals("Enter Username")) {
            jTextField1.setCaretPosition(0);
        }
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        char keyChar = evt.getKeyChar();
        if (jTextField1.getText().trim().equals("Enter Username") && Character.isLetterOrDigit(keyChar) && !Character.isWhitespace(keyChar)) {
            jTextField1.setText(null);
            jTextField1.setForeground(new Color(0x0000));
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField1FocusLost
        if (jTextField1.getText().trim().isEmpty()) {
            jTextField1.setText("Enter Username");
            jTextField1.setForeground(new Color(0x8D8D8D));
        }
    }//GEN-LAST:event_jTextField1FocusLost

    private void jPasswordField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPasswordField1MouseClicked
        if (jPasswordField1.getText().equals("Enter Password")) {
            jPasswordField1.setCaretPosition(0);
        }
    }//GEN-LAST:event_jPasswordField1MouseClicked

    private void jPasswordField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyPressed
        char keyChar = evt.getKeyChar();
        if (jPasswordField1.getText().equals("Enter Password") && Character.isLetterOrDigit(keyChar) && !Character.isWhitespace(keyChar)) {
            jPasswordField1.setText(null);
            jPasswordField1.setForeground(new Color(0x0000));
            jPasswordField1.setEchoChar('*');
        }
    }//GEN-LAST:event_jPasswordField1KeyPressed

    private void jPasswordField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPasswordField1FocusLost
        if (jPasswordField1.getText().trim().isEmpty()) {
            jPasswordField1.setEchoChar((char) 0);
            jPasswordField1.setText("Enter Password");
            jPasswordField1.setForeground(new Color(0x8D8D8D));
        }
    }//GEN-LAST:event_jPasswordField1FocusLost

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        if (jTextField1.getText().trim().equals("Enter Username")) {
            jTextField1.setText("Enter Username");
            jTextField1.setCaretPosition(0);
        }
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jPasswordField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1KeyReleased
        if (jPasswordField1.getText().trim().equals("Enter Password")) {
            jPasswordField1.setText("Enter Password");
            jPasswordField1.setCaretPosition(0);
        }
    }//GEN-LAST:event_jPasswordField1KeyReleased

    private void username_Validation(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_username_Validation
        // Validation: Maximum characters of 40 
        String n = jTextField1.getText();
        int l1 = n.length();
        char c1 = evt.getKeyChar();

        if (Character.isLetterOrDigit(c1)) {
            if (l1 < 40) {
                jTextField1.setEditable(true);
            } else {
                jTextField1.setEditable(false);
            }
        } else {
            if (Character.isWhitespace(c1) || Character.isISOControl(c1) || evt.getExtendedKeyCode() == KeyEvent.VK_2 || evt.getExtendedKeyCode() == KeyEvent.VK_SHIFT) {
                jTextField1.setEditable(true);
            } else {
                jTextField1.setEditable(false);
            }
        }
    }//GEN-LAST:event_username_Validation

    private void password_Validation(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_password_Validation
        // Validation: Maximum characters of 40 
        String n = jPasswordField1.getText();
        int l1 = n.length();
        char c1 = evt.getKeyChar();

        if (Character.isLetterOrDigit(c1)) {
            if (l1 < 40) {
                jPasswordField1.setEditable(true);
            } else {
                jPasswordField1.setEditable(false);
            }
        } else {
            if (Character.isWhitespace(c1) || Character.isISOControl(c1) || evt.getExtendedKeyCode() == KeyEvent.VK_2 || evt.getExtendedKeyCode() == KeyEvent.VK_SHIFT) {
                jPasswordField1.setEditable(true);
            } else {
                jPasswordField1.setEditable(false);
            }
        }
    }//GEN-LAST:event_password_Validation

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new loginFrame().setVisible(true);
            }
        });
    }
    public static int pic = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
